"""Prometheus Metrics configuration and counters for AI Chatbot backend."""
from prometheus_client import Counter, Histogram

# --- Token Metrics ---
PROMPT_TOKENS_TOTAL = Counter(
    "chat_llm_prompt_tokens_total",
    "Total prompt tokens sent to LLM",
    ["provider", "model"],
)

COMPLETION_TOKENS_TOTAL = Counter(
    "chat_llm_completion_tokens_total",
    "Total completion tokens generated by LLM",
    ["provider", "model"],
)

TOKENS_TOTAL = Counter(
    "chat_llm_tokens_total",
    "Total tokens consumed (prompt + completion)",
    ["provider", "model"],
)

# --- Chat & Conversation Metrics ---
CONVERSATIONS_CREATED_TOTAL = Counter(
    "chat_conversations_created_total",
    "Total number of chat conversations created",
)

CONVERSATIONS_DELETED_TOTAL = Counter(
    "chat_conversations_deleted_total",
    "Total number of chat conversations deleted",
)

MESSAGES_TOTAL = Counter(
    "chat_messages_total",
    "Total number of messages created",
    ["role"],
)

# --- Latency & Performance Histograms ---
LLM_REQUEST_DURATION_SECONDS = Histogram(
    "chat_llm_request_duration_seconds",
    "LLM response generation duration in seconds",
    ["provider", "status"],
)

LLM_TIME_TO_FIRST_TOKEN_SECONDS = Histogram(
    "chat_llm_time_to_first_token_seconds",
    "Time to first token (TTFT) for streaming responses in seconds",
    ["provider"],
)

HTTP_REQUEST_DURATION_SECONDS = Histogram(
    "chat_http_request_duration_seconds",
    "HTTP request duration in seconds",
    ["method", "endpoint"],
)


def record_tokens(provider: str, model: str, prompt_tokens: int, completion_tokens: int) -> None:
    """Record prompt, completion, and total token usage metrics."""
    PROMPT_TOKENS_TOTAL.labels(provider=provider, model=model).inc(prompt_tokens)
    COMPLETION_TOKENS_TOTAL.labels(provider=provider, model=model).inc(completion_tokens)
    TOKENS_TOTAL.labels(provider=provider, model=model).inc(prompt_tokens + completion_tokens)


def record_message(role: str) -> None:
    """Record message metric tagged by role (user/assistant)."""
    MESSAGES_TOTAL.labels(role=role).inc()


def record_conversation_created() -> None:
    """Record conversation creation metric."""
    CONVERSATIONS_CREATED_TOTAL.inc()


def record_conversation_deleted() -> None:
    """Record conversation deletion metric."""
    CONVERSATIONS_DELETED_TOTAL.inc()
